name: imkonjob_server
description: Imkon Job backend API (Dart Frog)
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.4.0

dev_dependencies:
  dart_frog_gen: ^1.4.0
  test: ^1.24.0
